"""Initial schema.

Represents the current application schema exactly. Written by hand rather than
autogenerated, because the details matter:

* ``JSONB`` on PostgreSQL, plain ``JSON`` on SQLite, so one revision serves both.
* ``server_default`` alongside the Python-side default, so a row inserted
  outside the ORM (a migration, a psql session) still gets a sensible value.
* CHECK constraints on the enum-like columns, so an invalid status is rejected
  by the database and not only by application validation.
* Indexes chosen from the queries the application actually runs.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-26
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def _json() -> sa.types.TypeEngine:
    """JSONB on PostgreSQL, plain JSON on SQLite (no JSONB equivalent)."""
    return postgresql.JSONB().with_variant(sa.JSON(), "sqlite")


def _created() -> sa.Column:
    return sa.Column(
        "created_at", sa.DateTime(timezone=True),
        server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False,
    )


def _updated() -> sa.Column:
    return sa.Column(
        "updated_at", sa.DateTime(timezone=True),
        server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False,
    )


def _ws_fk() -> sa.ForeignKeyConstraint:
    return sa.ForeignKeyConstraint(
        ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
    )


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


#: conversations.question_id -> open_questions.id and
#: open_questions.conversation_id -> conversations.id form a cycle, so neither
#: table can be created first while both constraints are inline.
#:
#: SQLite permits a forward reference (it is only checked at insert time), so
#: the constraint is declared inline there. PostgreSQL rejects the CREATE
#: outright, so the constraint is added by ALTER TABLE once the target exists --
#: which is why downgrade() is safe to run in either order.
_CIRCULAR_FK_NAME = "fk_conversations_question_id_open_questions"


def upgrade() -> None:
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        _created(),
        _updated(),
    )

    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300),
                  server_default="New conversation", nullable=False),
        sa.Column("mode", sa.String(length=20), server_default="explore", nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.Column("archived", sa.Boolean(),
                  server_default=sa.text("false"), nullable=False),
        _created(),
        _updated(),
        _ws_fk(),
        # See _CIRCULAR_FK_NAME: inline on SQLite, added by ALTER on PostgreSQL.
        *([] if _is_postgres() else [
            sa.ForeignKeyConstraint(
                ["question_id"], ["open_questions.id"], ondelete="SET NULL"
            )
        ]),
        sa.CheckConstraint(
            "mode IN ('explore', 'investigate', 'apply')", name="ck_conversations_mode"
        ),
    )
    op.create_index("ix_conversations_workspace_id", "conversations", ["workspace_id"])
    op.create_index("ix_conversations_workspace_updated", "conversations",
                    ["workspace_id", "updated_at"])

    op.create_table(
        "repositories",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("local_path", sa.String(length=1000), nullable=False),
        sa.Column("branch", sa.String(length=200), server_default="main", nullable=False),
        sa.Column("kind", sa.String(length=20), server_default="source", nullable=False),
        sa.Column("writable", sa.Boolean(),
                  server_default=sa.text("false"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        _created(),
        _updated(),
        _ws_fk(),
        sa.UniqueConstraint("workspace_id", "name", name="uq_repo_ws_name"),
        sa.CheckConstraint(
            "kind IN ('documentation', 'source')", name="ck_repositories_kind"
        ),
    )
    op.create_index("ix_repositories_workspace_id", "repositories", ["workspace_id"])

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=True),
        sa.Column("citations", _json(), nullable=True),
        sa.Column("tool_calls", _json(), nullable=True),
        _created(),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.CheckConstraint(
            "role IN ('user', 'assistant', 'system')", name="ck_messages_role"
        ),
    )
    op.create_index("ix_messages_conversation_id", "messages", ["conversation_id"])
    op.create_index("ix_messages_created_at", "messages", ["created_at"])

    op.create_table(
        "open_questions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        # A real UUID: native 16 bytes on PostgreSQL, CHAR(32) on SQLite.
        sa.Column("uid", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("evidence", _json(), nullable=True),
        sa.Column("affected", _json(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="open", nullable=False),
        sa.Column("source", sa.String(length=20), server_default="manual", nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        _created(),
        _updated(),
        _ws_fk(),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="SET NULL"
        ),
        sa.CheckConstraint(
            "status IN ('open', 'answered', 'resolved')", name="ck_open_questions_status"
        ),
    )
    op.create_index("ix_open_questions_workspace_id", "open_questions", ["workspace_id"])
    # UNIQUE, not merely indexed: this is what enforces the uid uniqueness.
    op.create_index("ix_open_questions_uid", "open_questions", ["uid"], unique=True)

    # The other half of the circular reference, now that both tables exist.
    if _is_postgres():
        op.create_foreign_key(
            _CIRCULAR_FK_NAME,
            "conversations",
            "open_questions",
            ["question_id"],
            ["id"],
            ondelete="SET NULL",
        )

    op.create_table(
        "decisions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("context", sa.Text(), server_default="", nullable=False),
        sa.Column("decision", sa.Text(), server_default="", nullable=False),
        sa.Column("rationale", sa.Text(), server_default="", nullable=False),
        sa.Column("consequences", sa.Text(), server_default="", nullable=False),
        sa.Column("status", sa.String(length=20),
                  server_default="proposed", nullable=False),
        sa.Column("decided_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("markdown_path", sa.String(length=1000), nullable=True),
        sa.Column("related_documents", _json(), nullable=True),
        sa.Column("related_questions", _json(), nullable=True),
        _created(),
        _updated(),
        _ws_fk(),
        sa.CheckConstraint(
            "status IN ('proposed', 'approved', 'rejected', 'superseded')",
            name="ck_decisions_status",
        ),
    )
    op.create_index("ix_decisions_workspace_id", "decisions", ["workspace_id"])

    op.create_table(
        "change_proposals",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=30), server_default="edit", nullable=False),
        sa.Column("title", sa.String(length=300), server_default="", nullable=False),
        sa.Column("reason", sa.Text(), server_default="", nullable=False),
        sa.Column("evidence", _json(), nullable=True),
        sa.Column("changes", _json(), nullable=True),
        sa.Column("expected_consequences", sa.Text(), server_default="", nullable=False),
        sa.Column("diff", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        _created(),
        _updated(),
        _ws_fk(),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="SET NULL"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected')",
            name="ck_change_proposals_status",
        ),
    )
    op.create_index("ix_change_proposals_workspace_id", "change_proposals",
                    ["workspace_id"])
    op.create_index("ix_change_proposals_conversation", "change_proposals",
                    ["conversation_id"])
    op.create_index("ix_change_proposals_workspace_status", "change_proposals",
                    ["workspace_id", "status"])

    op.create_table(
        "inventory_runs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        _created(),
        _updated(),
        _ws_fk(),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')",
            name="ck_inventory_runs_status",
        ),
    )
    op.create_index("ix_inventory_runs_workspace_id", "inventory_runs", ["workspace_id"])

    op.create_table(
        "inventory_items",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("source_path", sa.String(length=1000), nullable=False),
        sa.Column("purpose", sa.Text(), server_default="", nullable=False),
        sa.Column("suggested_path", sa.String(length=1000), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("overlaps", _json(), nullable=True),
        sa.Column("ambiguous", sa.Boolean(),
                  server_default=sa.text("false"), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("decision", sa.String(length=20), server_default="pending", nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["inventory_runs.id"], ondelete="CASCADE"),
        sa.CheckConstraint(
            "decision IN ('pending', 'applied', 'skipped')",
            name="ck_inventory_items_decision",
        ),
    )
    op.create_index("ix_inventory_items_run_id", "inventory_items", ["run_id"])


def downgrade() -> None:
    # Reverse dependency order, dropping the circular foreign key first:
    # conversations.question_id still references open_questions, so dropping
    # open_questions before releasing that constraint fails. SQLite needs the
    # batch mode enabled in env.py for the same reason.
    if _is_postgres():
        op.drop_constraint(
            _CIRCULAR_FK_NAME, "conversations", type_="foreignkey"
        )
    op.drop_table("inventory_items")
    op.drop_table("inventory_runs")
    op.drop_table("change_proposals")
    op.drop_table("decisions")
    op.drop_table("messages")
    op.drop_table("open_questions")
    op.drop_table("repositories")
    op.drop_table("conversations")
    op.drop_table("workspaces")